name: Send Daily Reminders

on:
  schedule:
    - cron: '*/1 * * * *'  # every 5 minutes

  workflow_dispatch:

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sendgrid

      - name: Run reminder script
        run: python send_due_reminders.py
